site_name: mkdocs-techdocs-redirects
description: A TechDocs website for mkdocs-techdocs-redirects
docs_dir: docs
repo_url: https://github.com/matchaxnb/mkdocs-techdocs-redirect/
plugins:
  - techdocs-core
  - redirects:
      redirect_maps:
        tutorial: tutorial/01-getting-started
        redirection_example: index

