name: CI
on:
  push:
  pull_request:
  schedule:
    - cron: '0 6 * * 6'
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - python: '^3.10'
            os: ubuntu-latest
          - python: 3.9
            os: windows-latest
          - python: 3.8
            os: ubuntu-latest
          - python: 3.7
            os: macos-latest
          - python: 3.6
            os: windows-latest
          - python: 3.6
            os: ubuntu-latest
            versions: minimal
    runs-on: ${{matrix.os}}
    steps:
      - name: Download source
        uses: actions/checkout@v3
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{matrix.python}}
      - name: Pin to lowest versions
        if: matrix.versions == 'minimal'
        run: |
          sed -i -E "s/^ +'(\\w+)>=([0-9])/'\\1==\\2/" setup.py
      - name: Install packages
        run: |
          python -m pip install -U pip'>=19'
          pip install -U --upgrade-strategy=eager .[test]
      - name: Test
        run: |
          .tools/ci.sh with_groups
      - name: Check formatting
        if: matrix.versions == null
        run: |
          git diff --exit-code
